### get all users

GET http://localhost:3000/api/users

### get a single user
GET http://localhost:3000/api/users/1

### create a single user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "email": "something email",
  "password": "something password",
  "name": "something name",
  "surname": "something surname"
}


### update a single user
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
  "name": "this is my new name"
}

### delete a single user
DELETE http://localhost:3000/api/users/14