import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Gestion de Usuarios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.ico" />
      </Head>      
      <main className={styles.main}>
        <div className={styles.login_container}>
          <div className={styles.info_login}>
            <Image
              src="/logo cice con slogan.png"
              alt="CICE Logo"
              className={styles.logo_Cice}
              width={300}
              height={150}
            />
          </div>

          <div className={styles.login_form_container}>
            <form className={styles.form_login} action="">
              <div className={styles.titulo}>
                  <h2>INICIAR SESION</h2>
              </div>
             {/*  <div className={styles.inputLog}>
                  <div className={styles.labInput}>
                    <label className={styles.label}> Email </label>
                    <input className={styles.input} type="text" name='Email'> </input> 
                  </div>
                  <div className={styles.labInput}>
                    <label className={styles.label}> Contraseña</label>
                    <div className={styles.eye_password}>
                      <input className={styles.input_eye} type="password" name='pass' id="password_input"></input>
                        <svg id="eye" onclick="showpassword()" width="35" height="35" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                          <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path>
                          <path d="M12 9a3 3 0 1 0 0 6 3 3 0 1 0 0-6z"></path>
                        </svg>
                    </div>
                    <a id="FgPass" href="">¿Olvidaste tu contraseña?</a>
                  </div>
              </div>
              <div className={styles.button_volver}>
                <button class="button">INGRESAR</button>
                <a>¿No sos usuario?</a>
                <button class="button">REGISTRARSE</button>
              </div> */}
            </form>
          </div>
        </div>

        
      {/* <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div> */}

        
      </main>    
    </>
  )
}
