import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })

export default function App({ Component, pageProps }) {
  return <>
      <style jsx global>{`
        html {
          font-family: ${inter.style.fontFamily};
        }
      `}</style>
      <Head>
        <title>CICE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  
       <ToastContainer 
              position="top-right"
              autoClose={5000}
              hideProgressBar={false}
              newestOnTop={true}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            /> 
      <Component {...pageProps} />
    </>
}
